# Generated by Django 5.0.6 on 2024-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="game_thumbnails/"
            ),
        ),
    ]
