# Generated by Django 5.0.6 on 2024-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
