# Generated by Django 5.0.6 on 2024-06-30 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="difficulty_rating",
        ),
        migrations.RemoveField(
            model_name="game",
            name="play_time",
        ),
        migrations.RemoveField(
            model_name="game",
            name="player_count",
        ),
        migrations.AddField(
            model_name="game",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="max_players",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="max_playtime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_players",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_playtime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.RenameModel(
            old_name="Nomination",
            new_name="GameNomination",
        ),
        migrations.CreateModel(
            name="GameSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_signed_up", models.DateTimeField(auto_now_add=True)),
                (
                    "nomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boardgame.gamenomination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("nomination", "user")},
            },
        ),
    ]
