# Generated by Django 5.0.6 on 2024-07-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlocation",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
