# Generated by Django 5.0.6 on 2024-07-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0002_eventlocation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
