# Generated by Django 5.0.6 on 2024-06-30 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "boardgame",
            "0002_remove_game_difficulty_rating_remove_game_play_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="age",
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
