# Generated by Django 5.0.6 on 2024-06-28 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0002_event_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="slug",
        ),
    ]
