# Generated by Django 5.0.6 on 2024-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0002_alter_game_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamecomment",
            old_name="timestamp",
            new_name="date_added",
        ),
        migrations.AlterField(
            model_name="game",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
