# Generated by Django 5.0.6 on 2024-07-11 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0003_group_group_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouplocation",
            name="postcode",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
