# Generated by Django 5.0.6 on 2024-07-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0003_rename_timestamp_gamecomment_date_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="game_thumbnails/"
            ),
        ),
    ]
