# Generated by Django 5.0.6 on 2024-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0003_alter_game_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
