# Generated by Django 5.0.6 on 2024-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0005_alter_game_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="weight",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
