# Generated by Django 5.0.6 on 2024-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0006_alter_game_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="nominations",
            field=models.ManyToManyField(
                through="boardgame.GameNomination", to="boardgame.game"
            ),
        ),
    ]
