# Generated by Django 5.0.6 on 2024-07-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0006_alter_game_thumbnail_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="thumbnail_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="game_thumbnails/"
            ),
        ),
    ]
