# Generated by Django 5.0.6 on 2024-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0006_eventlocation_sublocality"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_image",
            field=models.ImageField(blank=True, null=True, upload_to="group_images/"),
        ),
    ]
