# Generated by Django 5.0.6 on 2024-07-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0007_event_nominations"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(blank=True, upload_to="profile_images"),
        ),
    ]
