# Generated by Django 5.0.6 on 2024-07-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0010_groupmembers_is_moderator"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_privacy",
            field=models.CharField(
                choices=[("0", "Public"), ("1", "Private")], default=0, max_length=10
            ),
            preserve_default=False,
        ),
    ]
