# Generated by Django 5.0.6 on 2024-07-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0011_group_group_privacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_privacy",
            field=models.CharField(
                choices=[("Public", "Public"), ("Private", "Private")],
                default="Public",
                max_length=10,
            ),
        ),
    ]
