# Generated by Django 5.0.6 on 2024-07-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0012_alter_group_group_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembers",
            name="member_status",
            field=models.CharField(
                choices=[("Requested", "Requested"), ("Accepted", "Accepted")],
                default="Accepted",
                max_length=10,
            ),
        ),
    ]
