# Generated by Django 5.0.6 on 2024-07-18 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0013_groupmembers_member_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmembers",
            name="member_status",
        ),
    ]
