# Generated by Django 5.0.6 on 2024-07-18 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0014_remove_groupmembers_member_status"),
    ]

    operations = []
