# Generated by Django 5.0.6 on 2024-07-18 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0015_auto_20240718_0216"),
    ]

    operations = []
