# Generated by Django 5.0.6 on 2024-07-20 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "boardgame",
            "0018_event_admin_only_nominations_event_nominations_open_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamesignup",
            old_name="nomination",
            new_name="game",
        ),
        migrations.AlterUniqueTogether(
            name="gamesignup",
            unique_together={("game", "user")},
        ),
    ]
