# Generated by Django 5.0.6 on 2024-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0022_alter_vote_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="profile", to="boardgame.category"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_games",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="profile", to="boardgame.tag"
            ),
        ),
    ]
