# Generated by Django 5.0.6 on 2024-07-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardgame", "0024_userlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name="UserLocation",
        ),
    ]
